# Test order specify here what should be executed
#
# load all data sets, else TRAIN_SETTING or TEST_SETTING (files which are written in setting file)
load all
define trainSet as classes all from TRAIN_SETTING
#define train0 without classes 2 from TRAIN_SETTING
#define train1 as classes 2 from TRAIN_SETTING
define test0 as classes all from TEST_SETTING
train trainSet for 30 m with only 10 mb
test trainSet
test test0